# Generated by Django 4.2.30 on 2026-05-28 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0002_approvalrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLlmConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(blank=True, default='', max_length=300)),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_llm_config',
            },
        ),
    ]
