# Generated by Django 4.2 on 2026-05-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_userllmconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentsession",
            name="conversation_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="agentsession",
            name="summary_through_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
