# Generated by Django 4.2.30 on 2026-06-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_agentsession_conversation_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userllmconfig',
            name='asr_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userllmconfig',
            name='tts_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userllmconfig',
            name='tts_voice',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
