# Generated by Django 4.2.30 on 2026-06-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_userllmconfig_asr_model_userllmconfig_tts_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userllmconfig',
            name='asr_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userllmconfig',
            name='asr_base_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userllmconfig',
            name='tts_api_key',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='userllmconfig',
            name='tts_base_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
